[denops-vim]
src.github = "vim-denops/denops.vim"
fetch.github = "vim-denops/denops.vim"

[neotest]
src.github = "nvim-neotest/neotest"
fetch.github = "nvim-neotest/neotest"

[nvim-nio]
src.github = "nvim-neotest/nvim-nio"
fetch.github = "nvim-neotest/nvim-nio"

[neotest-golang]
src.github = "fredrikaverpil/neotest-golang"
fetch.github = "fredrikaverpil/neotest-golang"

[plenary-nvim]
src.git = "https://github.com/nvim-lua/plenary.nvim.git"
fetch.github = "nvim-lua/plenary.nvim"

[popup-nvim]
src.git = "https://github.com/nvim-lua/popup.nvim.git"
fetch.github = "nvim-lua/popup.nvim"

[nvim-coverage]
src.git = "https://github.com/andythigpen/nvim-coverage"
fetch.github = "andythigpen/nvim-coverage"

[statuscol-nvim]
src.git = "https://github.com/luukvbaal/statuscol.nvim"
fetch.github = "luukvbaal/statuscol.nvim"

[neotest-plenary]
src.git = "https://github.com/nvim-neotest/neotest-plenary"
fetch.github = "nvim-neotest/neotest-plenary"

[nvim-dap-go]
src.git = "https://github.com/leoluz/nvim-dap-go"
fetch.github = "leoluz/nvim-dap-go"

[nvim-dap]
src.git = "https://github.com/mfussenegger/nvim-dap"
fetch.github = "mfussenegger/nvim-dap"

[nvim-dap-ui]
src.git = "https://github.com/rcarriga/nvim-dap-ui"
fetch.github = "rcarriga/nvim-dap-ui"

[nvim-dap-virtual-text]
src.git = "https://github.com/theHamsta/nvim-dap-virtual-text"
fetch.github = "theHamsta/nvim-dap-virtual-text"

[jdim]
src.github = "JDimproved/JDim"
fetch.github = "JDimproved/JDim"

[anthropics-skills]
src.git = "https://github.com/anthropics/skills"
fetch.github = "anthropics/skills"

[atusy-dotfiles]
src.git = "https://github.com/atusy/dotfiles"
fetch.github = "atusy/dotfiles"

[claudecodeui]
src.github = "siteboon/claudecodeui"
fetch.github = "siteboon/claudecodeui"

[codecompanion-nvim]
src.github = "olimorris/codecompanion.nvim"
fetch.github = "olimorris/codecompanion.nvim"
