[denops-vim]
src.github = "vim-denops/denops.vim"
fetch.github = "vim-denops/denops.vim"

[neotest]
src.github = "nvim-neotest/neotest"
fetch.github = "nvim-neotest/neotest"

[nvim-nio]
src.github = "nvim-neotest/nvim-nio"
fetch.github = "nvim-neotest/nvim-nio"

[neotest-golang]
src.github = "fredrikaverpil/neotest-golang"
fetch.github = "fredrikaverpil/neotest-golang"

[plenary-nvim]
src.git = "https://github.com/nvim-lua/plenary.nvim.git"
fetch.github = "nvim-lua/plenary.nvim"

[popup-nvim]
src.git = "https://github.com/nvim-lua/popup.nvim.git"
fetch.github = "nvim-lua/popup.nvim"

[nvim-coverage]
src.git = "https://github.com/andythigpen/nvim-coverage"
fetch.github = "andythigpen/nvim-coverage"

[statuscol-nvim]
src.git = "https://github.com/luukvbaal/statuscol.nvim"
fetch.github = "luukvbaal/statuscol.nvim"

[neotest-plenary]
src.git = "https://github.com/nvim-neotest/neotest-plenary"
fetch.github = "nvim-neotest/neotest-plenary"

[avante-nvim]
src.git = "https://github.com/yetone/avante.nvim"
fetch.github = "yetone/avante.nvim"
