[treesitter]
src.git = "https://github.com/nvim-treesitter/nvim-treesitter.git"
src.branch = "main"
fetch.github = "nvim-treesitter/nvim-treesitter"

[denops]
src.github = "vim-denops/denops.vim"
fetch.github = "vim-denops/denops.vim"
