[[plugins]]
repo = "neovim/nvim-lspconfig"
hooks_file = ["$BASE_DIR/dpp/nvim_lsp.lua"]

[[plugins]]
repo = "hrsh7th/nvim-gtd"
lua_add = '''
require('gtd').setup({})
'''

[[plugins]]
repo = "b0o/schemastore.nvim"

[[plugins]]
repo = "ray-x/lsp_signature.nvim"

[[plugins]]
repo = "creativenull/efmls-configs-nvim"

[[plugins]]
repo = "uga-rosa/ddc-source-lsp-setup"
