---
name: Check
on:
  pull_request:
  push:
    branches: [main]
jobs:
  flake-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - uses: cachix/cachix-action@18cf96c7c98e048e10a83abd92116114cd8504be # v14
        with:
          name: gamoutatsumi
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1.2.1
        with:
          arguments: --accept-flake-config
      - run: nix flake check --accept-flake-config
      - name: Check diff
        id: diff
        run: |
          git diff --name-only --exit-code
        continue-on-error: true
      - uses: suzuki-shunsuke/commit-action@87b297f0ce551411b43d1880f4fb3cbc60381055 # v0.0.14
        if: steps.diff.outcome == 'failure' && github.event_name == 'pull_request'
        with:
          app_id: ${{ secrets.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
          files: |
            flake.lock
          commit_message: |-
            Update flake.lock
      - uses: natsukium/nix-diff-action@374bf5037dc84fc520da2002beef2f2bd96f4e9b # v1.0.2
        if: github.event_name == 'pull_request'
        with:
          attributes: |-
            - displayName: nixos-desktop
              attribute: nixosConfigurations.tat-nixos-desktop.config.system.build.toplevel
            - displayName: nixos-laptop
              attribute: nixosConfigurations.tat-nixos-laptop.config.system.build.toplevel
